# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ci

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0      

      - name: Install dependencies
        run: npm ci

      - name: Lint 
        run: npm run lint

      # - name: Test 
      #   run: npm run test    

      - name: Build 
        run: npm run build

      - name: Run Action 
        uses: ./
        with:
          version: 'latest'
          token: ${{ github.token }}

      - name: Publish
        run: v version

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: setup-v
          generateReleaseNotes: true
          body: ${{steps.build_changelog.outputs.changelog}}
          token: ${{ secrets.GITHUB_TOKEN }}